name: sign-binary
run-name: "Sign ${{ github.ref }} binary"

on:
  push: {} # FIXME
  release:
    types: [published]

env:
  VAULT_ADDR: ${{ vars.VAULT_ADDR }}
  VAULT_NAMESPACE: ${{ vars.VAULT_NAMESPACE }}
  environment: prod

jobs:
  sign-binary:
    runs-on: windows-latest
    environment: prod
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Vault CLI
        shell: powershell
        run: |
          Invoke-WebRequest -OutFile "vault.zip" -Uri "https://releases.hashicorp.com/vault/1.16.1/vault_1.16.1_windows_amd64.zip"
          Expand-Archive -Path "vault.zip" -DestinationPath .
          Remove-Item "vault.zip"

      - name: Authenticate to Vault
        uses: hashicorp/vault-action@v2
        with:
          url: ${{ env.VAULT_ADDR }}
          namespace: ${{ env.VAULT_NAMESPACE }}
          method: jwt
          path: gh-actions
          role: repository
          jwtGithubAudience: ${{ env.VAULT_ADDR }}
          exportToken: true

      - name: Get code signing certificate
        shell: powershell
        run: |
          $Endpoint = "pki-codesign/issue/github-actions"
          $CertSubject = "spiffe://github.com/${{ github.repository }}@${{ env.environment }}"
          $Cert = $(./vault.exe write -format=json "$Endpoint" common_name="$CertSubject" uri_sans="$CertSubject")
          $CertJson = $Cert | ConvertFrom-Json
          Set-Content -Path "codesigning.crt" -Value "$($CertJson.data.certificate)`n$($CertJson.data.ca_chain -Join "`n")"
          Set-Content -Path "codesigning.key" -Value "$($CertJson.data.private_key)"
          openssl pkcs12 -export -out codesigning.pfx -inkey codesigning.key -in codesigning.crt -passout pass:""
          Import-PfxCertificate -FilePath "codesigning.pfx" -CertStoreLocation Cert:\CurrentUser\My
          Remove-Item codesigning.crt codesigning.key codesigning.pfx

      - name: Sign binary
        shell: powershell
        run: |
          $Cert = Get-ChildItem Cert:\CurrentUser\My -CodeSigningCert | Select-Object -First 1
          Set-AuthenticodeSignature `
            -Certificate $Cert `
            -FilePath "smallexe64.exe" `
            -TimestampServer "http://timestamp.digicert.com"

      - name: Upload signed binary
        uses: actions/upload-artifact@v2
        with:
          name: signed-binary
          path: smallexe64.exe
